spring:
  profiles: test-peer2
server:
  port: 8762

eureka:
  instance:
  client:
    service-url:
      defaultZone: http://172.16.10.177:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
#  server:
#    enable-self-preservation: false
