spring:
  profiles: peer2
server:
  port: 8762

eureka:
  instance:
    hostname: 192.168.0.167
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    register-with-eureka: false
    fetch-registry: false