#spring:
#  profiles: test-peer1

server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
       defaultZone: http://172.16.10.177:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

#  server:
#    enable-self-preservation: false
