spring:
  application:
    name: client-feign
server:
  port: 8765
eureka:
  client:
    service-url:
      serviceZone: http://localhost:8761/eureka/

# 在Feign客户端开启Hystrix的支持
# feign.hystrix.enabled=true
feign:
  hystrix:
    enabled: true

