spring:
  application:
    name: client-turbine-monitor
server:
  port: 8767
eureka:
  client:
    service-url:
      serviceZone: http://localhost:8761/eureka/

# turbine的配置参阅过 https://segmentfault.com/a/1190000011478978
turbine:
  app-config: client-feign,client-order-ribbon,client-gateway-zuul # 指定了要监控的应用名字
  cluster-name-expression: new String("default") # 表示集群的名字为default
  combine-host-port: true # 表示同一主机上的服务通过host和port的组合来进行区分，默认情况下是使用host来区分，这样会使本地调试有问题
  instanceUrlSuffix: hystrix.stream

management:
  context-path: /

# 这里解决 /actuator/hystrix.stream 访问不了问题
# http://blog.didispace.com/spring-cloud-tips-4/


